#greeting: Welcome to my file configurable application
db_host:
  development: localhost
  test: localhost
  production: localhost
db_port:
  development: 3306
  test: 3306
  production: 3306  
db_name:
  development: sts
  test: sts
  production: sts
